### ISSUE TITLE
pcie display doesn't work for pioneer pcb 1.1

### ISSUE THREAD

**Issue by unicornx** [sophgo/linux-riscv#113]
I found on sg2042-dev branch, with commit: "e7d0ed665196 drivers: pci: support msix in PCIe rc0 for milkv mainboard" in, my pioneer pcb 1.1 does't work when connecting display with the pcie port.
But when I rollback to "4973498c7073 drm/amd/display: Support DRM_AMD_DC_FP on RISC-V", it does work.

**Comment by xingxg2022** [comment]
if you have pionner pcb 1.1 or pcb 1.2，please revert "e7d0ed665196 drivers: pci: support msix in PCIe rc0 for milkv mainboard"

**Comment by unicornx** [comment]
ok, thanks.

Though I am very hoping you can support old pcb board on sg2042-dev.

Close this issue anyway.

**Comment by unicornx** [comment]
Originally the pcie card is in the socket near the DDR sockets. In latest design, only one of them can work.

Move the pcie card to another socket near the bottom of the box and this issue is resolved.
